config/routes.rb
Rails.application.routes.draw do
  

  resources :trip_todos
  resources :suggestions_box_trips
  resources :suggestions_box_hotels
  mount API::Base, at: "/"
  mount GrapeSwaggerRails::Engine, at: "/documentation"
  # mount GrapeSwaggerRails::Engine => '/swagger'

  resources :tasks
  get 'trip_suggestions' => "trip_suggestions#index"
  get 'hotel_suggestions' => "hotel_suggestions#index"
  get 'mytrips'  => "mytrips#index"
  get 'trips' => "trips#index"

  
 post '/createTrip' =>"trips#createTrip"

  root :to =>'home#index'
  # root to: 'receipts#index'


  # devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}
  
  devise_for :users
  get 'load_data/get_data_from_api' => 'load_data#get_data_from_api'
  get 'load_data/index' => 'load_data#index'
  
  #match '/receipts/:receipt_id/uploads/newupload' => 'uploads#newreceiptupload', via: :get, as: :new_receipt_upload

  resources :receipts do
    resources:uploads
  end
  
  resources :users do
    resources :receipts
  end
  
  resources :receipts do
    resources:products
  end
end

app/models/budget.rb
class Budget < ApplicationRecord
    
    validates :budgetamount, presence: true
    
    
end

app/models/budgetlist.rb
class Budgetlist < ApplicationRecord
    
     validates :budgetamount, presence: true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/load_data.rb
class LoadData < ApplicationRecord
   has_one :image
end
 

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :receipt
end

app/models/receipt.rb
class Receipt < ApplicationRecord
    has_many:products
    has_one :upload
   # has_one_attached :image
end
 

app/models/suggestions_box_hotel.rb
class SuggestionsBoxHotel < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/trip.rb
class Trip < ApplicationRecord

end

app/models/trip_todo.rb
class TripTodo < ApplicationRecord
end

app/models/upload.rb
class Upload < ApplicationRecord
    belongs_to :receipt, optional: true
    has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :receipts   
  
   devise :timeoutable
   
end

app/models/userbudget.rb
class Userbudget < ApplicationRecord
end

app/controllers/api/v1/suggestions_box_hotels.rb
module API
    module V1
      class SuggestionsBoxHotels < Grape::API
        include API::V1::Defaults
  
        resource :hotels_suggestions do

          desc "Return all hotels"
          get "", root: "hotels_suggestions" do
            ::SuggestionsBoxHotel.all
          end
  
          desc "Return a hotel"
          params do
            requires :id, type: String, desc: "ID of the hotel"
          end
          get ":id", root: "trips" do
            ::SuggestionsBoxHotel.where(id: permitted_params[:id]).first!
          end


        end

      end
    end
  end

app/controllers/suggestions_box_hotels_controller.rb
class SuggestionsBoxHotelsController < ApplicationController
  before_action :set_suggestions_box_hotel, only: [:show, :edit, :update, :destroy]

  # GET /suggestions_box_hotels
  # GET /suggestions_box_hotels.json
  def index
    @suggestions_box_hotels = SuggestionsBoxHotel.all
  end

  # GET /suggestions_box_hotels/1
  # GET /suggestions_box_hotels/1.json
  def show
  end

  # GET /suggestions_box_hotels/new
  def new
    @suggestions_box_hotel = SuggestionsBoxHotel.new
  end

  # GET /suggestions_box_hotels/1/edit
  def edit
  end

  # POST /suggestions_box_hotels
  # POST /suggestions_box_hotels.json
  def create
    @suggestions_box_hotel = SuggestionsBoxHotel.new(suggestions_box_hotel_params)

    respond_to do |format|
      if @suggestions_box_hotel.save
        format.html { redirect_to @suggestions_box_hotel, notice: 'Suggestions box hotel was successfully created.' }
        format.json { render :show, status: :created, location: @suggestions_box_hotel }
      else
        format.html { render :new }
        format.json { render json: @suggestions_box_hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suggestions_box_hotels/1
  # PATCH/PUT /suggestions_box_hotels/1.json
  def update
    respond_to do |format|
      if @suggestions_box_hotel.update(suggestions_box_hotel_params)
        format.html { redirect_to @suggestions_box_hotel, notice: 'Suggestions box hotel was successfully updated.' }
        format.json { render :show, status: :ok, location: @suggestions_box_hotel }
      else
        format.html { render :edit }
        format.json { render json: @suggestions_box_hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suggestions_box_hotels/1
  # DELETE /suggestions_box_hotels/1.json
  def destroy
    @suggestions_box_hotel.destroy
    respond_to do |format|
      format.html { redirect_to suggestions_box_hotels_url, notice: 'Suggestions box hotel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_suggestions_box_hotel
      @suggestions_box_hotel = SuggestionsBoxHotel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def suggestions_box_hotel_params
      params.require(:suggestions_box_hotel).permit(:hotel_name, :pernight, :decimal, :country, :city, :rating, :image, :buffet, :hall, :gym)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/load_data_helper.rb
module LoadDataHelper
end

app/helpers/mytrips_helper.rb
module MytripsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/helpers/suggestions_box_hotels_helper.rb
module SuggestionsBoxHotelsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/suggestions_box_hotels/_form.html.erb
<%= form_with(model: suggestions_box_hotel, local: true) do |form| %>
  <% if suggestions_box_hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(suggestions_box_hotel.errors.count, "error") %> prohibited this suggestions_box_hotel from being saved:</h2>

      <ul>
      <% suggestions_box_hotel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :hotel_name %>
    <%= form.text_field :hotel_name %>
  </div>

  <div class="field">
    <%= form.label :pernight %>
    <%= form.text_field :pernight %>
  </div>

  <div class="field">
    <%= form.label :decimal %>
    <%= form.text_field :decimal %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :buffet %>
    <%= form.check_box :buffet %>
  </div>

  <div class="field">
    <%= form.label :hall %>
    <%= form.check_box :hall %>
  </div>

  <div class="field">
    <%= form.label :gym %>
    <%= form.check_box :gym %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/suggestions_box_hotels/edit.html.erb
<h1>Editing Suggestions Box Hotel</h1>

<%= render 'form', suggestions_box_hotel: @suggestions_box_hotel %>

<%= link_to 'Show', @suggestions_box_hotel %> |
<%= link_to 'Back', suggestions_box_hotels_path %>

app/views/suggestions_box_hotels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Suggestions Box Hotels</h1>

<table>
  <thead>
    <tr>
      <th>Hotel name</th>
      <th>Pernight</th>
      <th>Decimal</th>
      <th>Country</th>
      <th>City</th>
      <th>Rating</th>
      <th>Image</th>
      <th>Buffet</th>
      <th>Hall</th>
      <th>Gym</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @suggestions_box_hotels.each do |suggestions_box_hotel| %>
      <tr>
        <td><%= suggestions_box_hotel.hotel_name %></td>
        <td><%= suggestions_box_hotel.pernight %></td>
        <td><%= suggestions_box_hotel.decimal %></td>
        <td><%= suggestions_box_hotel.country %></td>
        <td><%= suggestions_box_hotel.city %></td>
        <td><%= suggestions_box_hotel.rating %></td>
        <td><%= suggestions_box_hotel.image %></td>
        <td><%= suggestions_box_hotel.buffet %></td>
        <td><%= suggestions_box_hotel.hall %></td>
        <td><%= suggestions_box_hotel.gym %></td>
        <td><%= link_to 'Show', suggestions_box_hotel %></td>
        <td><%= link_to 'Edit', edit_suggestions_box_hotel_path(suggestions_box_hotel) %></td>
        <td><%= link_to 'Destroy', suggestions_box_hotel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Suggestions Box Hotel', new_suggestions_box_hotel_path %>

app/views/suggestions_box_hotels/new.html.erb
<h1>New Suggestions Box Hotel</h1>

<%= render 'form', suggestions_box_hotel: @suggestions_box_hotel %>

<%= link_to 'Back', suggestions_box_hotels_path %>

app/views/suggestions_box_hotels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hotel name:</strong>
  <%= @suggestions_box_hotel.hotel_name %>
</p>

<p>
  <strong>Pernight:</strong>
  <%= @suggestions_box_hotel.pernight %>
</p>

<p>
  <strong>Decimal:</strong>
  <%= @suggestions_box_hotel.decimal %>
</p>

<p>
  <strong>Country:</strong>
  <%= @suggestions_box_hotel.country %>
</p>

<p>
  <strong>City:</strong>
  <%= @suggestions_box_hotel.city %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @suggestions_box_hotel.rating %>
</p>

<p>
  <strong>Image:</strong>
  <%= @suggestions_box_hotel.image %>
</p>

<p>
  <strong>Buffet:</strong>
  <%= @suggestions_box_hotel.buffet %>
</p>

<p>
  <strong>Hall:</strong>
  <%= @suggestions_box_hotel.hall %>
</p>

<p>
  <strong>Gym:</strong>
  <%= @suggestions_box_hotel.gym %>
</p>

<%= link_to 'Edit', edit_suggestions_box_hotel_path(@suggestions_box_hotel) %> |
<%= link_to 'Back', suggestions_box_hotels_path %>