config/routes.rb
Rails.application.routes.draw do
  

  resources :trip_todos
  resources :suggestions_box_trips
  resources :suggestions_box_hotels
  mount API::Base, at: "/"
  mount GrapeSwaggerRails::Engine, at: "/documentation"
  # mount GrapeSwaggerRails::Engine => '/swagger'

  resources :tasks
  get 'trip_suggestions' => "trip_suggestions#index"
  get 'hotel_suggestions' => "hotel_suggestions#index"
  get 'mytrips'  => "mytrips#index"
  get 'trips' => "trips#index"

  
 post '/createTrip' =>"trips#createTrip"

  root :to =>'home#index'
  # root to: 'receipts#index'


  # devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}
  
  devise_for :users
  get 'load_data/get_data_from_api' => 'load_data#get_data_from_api'
  get 'load_data/index' => 'load_data#index'
  
  #match '/receipts/:receipt_id/uploads/newupload' => 'uploads#newreceiptupload', via: :get, as: :new_receipt_upload

  resources :receipts do
    resources:uploads
  end
  
  resources :users do
    resources :receipts
  end
  
  resources :receipts do
    resources:products
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/budget.rb
class Budget < ApplicationRecord
    
    validates :budgetamount, presence: true
    
    
end

app/models/budgetlist.rb
class Budgetlist < ApplicationRecord
    
     validates :budgetamount, presence: true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/load_data.rb
class LoadData < ApplicationRecord
   has_one :image
end
 

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :receipt
end

app/models/receipt.rb
class Receipt < ApplicationRecord
    has_many:products
    has_one :upload
   # has_one_attached :image
end
 

app/models/task.rb
class Task < ApplicationRecord
end

app/models/trip.rb
class Trip < ApplicationRecord

end

app/models/trip_todo.rb
class TripTodo < ApplicationRecord
end

app/models/upload.rb
class Upload < ApplicationRecord
    belongs_to :receipt, optional: true
    has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :receipts   
  
   devise :timeoutable
   
end

app/models/userbudget.rb
class Userbudget < ApplicationRecord
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/load_data_helper.rb
module LoadDataHelper
end

app/helpers/mytrips_helper.rb
module MytripsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/trip_todos_helper.rb
module TripTodosHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/load_data/get_data_from_api.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    
  <a class="navbar-brand" href="#">Expensease</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
    <a><%=link_to "Login", new_user_session_path, class: 'nav-link' %> </a>
      </li>
      <li class="nav-item">
        <!--<a class="nav-link" href="#">Pricing</a>-->
         <a> <%=link_to "Sign Up", new_user_registration_path, class: 'nav-link' %> </a>
      </li>
   
    </ul>
  </div>
</nav>


<center style="margin-top:35px">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            
     <h1><b>Upload Receipt</b></h1>
    <hr>
    <%= render 'receipts/form' %>
    <%= link_to 'Back', user_receipts_path(@user) %>  
            
        </div>
        <div class="col-md-4"></div>
        
    </div>
    

</center>

app/views/load_data/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <h2>New Receipt</h2>
   <a> <%=link_to "Create Receipt", new_user_receipt_path(@user), class: 'btn btn-primary' %> </a>
  <button type="button" class="btn btn-success" onclick="location.href='/loaddata/uploadfile'">UPLOAD RECEIPT</button>
</div>
</div>
</body>
</html>

app/views/load_data/uploadfile.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>
<center style="margin-top:35px">
    <div class="row">
        <div class="col-md-4"> </div>
            <% if !@user.errors.empty? %>
   <div class = "alert alert-error">
      
      <ul>
         <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>
      
   </div>
<% end %>

<div class = "well">
   <%= form_for @user, html: { multipart: true } do |f| %>
      <%= f.label :image %>
      <%= f.file_field :image %>
      <%= f.submit "Save", class: "btn btn-primary" %>
   <% end %>
    </div>
</center>
</body>
</html>

  
  
  
  
  

app/views/products/_form.html.erb
<%= form_for([@receipt, @product]) do |form| %>

  <% if @receipt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(receipt.errors.count, "error") %> prohibited this receipt from being saved:</h2>

      <ul>
      <% receipt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :productName %>
    <%= form.text_field :productName %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :unitPrice %>
    <%= form.text_field :unitPrice %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :totalPrice %>
    <%= form.text_field :totalPrice %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'products/form' %>
<%= link_to 'Back', user_receipt_path(@user, @receipt) %>

app/views/products/new.html.erb
<h1>New Product</h1>
<%= render 'form' %>
<%= link_to 'Back', user_receipt_path(@user, @receipt) %>

app/views/products/show.html.erb
<h1>Product was successfully updated.</h1>
<td><%= link_to 'Back', :back %></td>

app/views/uploads/_form.html.erb
<%= form_with(model: [@receipt, @upload], local: true) do |form| %>
<% if upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(upload.errors.count, "error") %> prohibited this upload from being saved:</h2>
      <ul>
      <% upload.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field form-group">
    <%= form.label :'Upload Receipt' %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/uploads/edit.html.erb
<h1>Editing Upload</h1>

<%= render 'form', upload: @upload %>

<%= link_to 'Show', home_index_path %> |
<%= link_to 'Back', home_index_path%>

app/views/uploads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Uploads</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>



<br>

app/views/uploads/new.html.erb
<h1>New Upload</h1>

<%= render 'form', upload: @upload %>

<%= link_to 'Back', root_path	%>

app/views/uploads/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Back', user_receipts_path(@user) %>