config/routes.rb
Rails.application.routes.draw do
  

  resources :trip_todos
  resources :suggestions_box_trips
  resources :suggestions_box_hotels
  mount API::Base, at: "/"
  mount GrapeSwaggerRails::Engine, at: "/documentation"
  # mount GrapeSwaggerRails::Engine => '/swagger'

  resources :tasks
  get 'trip_suggestions' => "trip_suggestions#index"
  get 'hotel_suggestions' => "hotel_suggestions#index"
  get 'mytrips'  => "mytrips#index"
  get 'trips' => "trips#index"

  
 post '/createTrip' =>"trips#createTrip"

  root :to =>'home#index'
  # root to: 'receipts#index'


  # devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}
  
  devise_for :users
  get 'load_data/get_data_from_api' => 'load_data#get_data_from_api'
  get 'load_data/index' => 'load_data#index'
  
  #match '/receipts/:receipt_id/uploads/newupload' => 'uploads#newreceiptupload', via: :get, as: :new_receipt_upload

  resources :receipts do
    resources:uploads
  end
  
  resources :users do
    resources :receipts
  end
  
  resources :receipts do
    resources:products
  end
end

app/models/budget.rb
class Budget < ApplicationRecord
    
    validates :budgetamount, presence: true
    
    
end

app/models/budgetlist.rb
class Budgetlist < ApplicationRecord
    
     validates :budgetamount, presence: true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/load_data.rb
class LoadData < ApplicationRecord
   has_one :image
end
 

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :receipt
end

app/models/receipt.rb
class Receipt < ApplicationRecord
    has_many:products
    has_one :upload
   # has_one_attached :image
end
 

app/models/task.rb
class Task < ApplicationRecord
end

app/models/trip.rb
class Trip < ApplicationRecord

end

app/models/trip_todo.rb
class TripTodo < ApplicationRecord
end

app/models/upload.rb
class Upload < ApplicationRecord
    belongs_to :receipt, optional: true
    has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :receipts   
  
   devise :timeoutable
   
end

app/models/userbudget.rb
class Userbudget < ApplicationRecord
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/load_data_helper.rb
module LoadDataHelper
end

app/helpers/mytrips_helper.rb
module MytripsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/layouts/application.html.erb
 <!--<p class="notice"><%= notice %></p>-->
 <!--   <p class="alert"><%= alert %></p>-->

<!DOCTYPE html>
<html>
  <head>
    <title>Plann</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  </head>

  <body>
      
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">

   <a><%=link_to "Plann", root_path, class: 'navbar-brand' %> </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
     
   
   <% if user_signed_in? %>
   
    <li class="nav-item active">
       <a><%=link_to "Create Trips", trips_path, class: 'nav-link' %> </a>
      </li>
   
      <li class="nav-item">
       <!--<a class="nav-link" href="#">Budget planner</a> -->
       <a><%=link_to "My Destination Trips", mytrips_path, class: 'nav-link' %> </a>
      </li>
      
      <li class="nav-item">
       <!--<a class="nav-link" href="#">Budget planner</a> -->
       <a><%=link_to "Trip suggestions", trip_suggestions_path, class: 'nav-link' %> </a>
      </li>

       <li class="nav-item">
       <!--<a class="nav-link" href="#">Budget planner</a> -->
       <a><%=link_to "Hotel suggestions", hotel_suggestions_path, class: 'nav-link' %> </a>
      </li>

      <li class="nav-item">
       <!--<a class="nav-link" href="#">Budget planner</a> -->
       <a><%=link_to "Add Hotel", new_suggestions_box_hotel_path, class: 'nav-link' %> </a>
      </li>

      <li class="nav-item">
       <!--<a class="nav-link" href="#">Budget planner</a> -->
       <a><%=link_to "Add Trip", new_suggestions_box_trip_path, class: 'nav-link' %> </a>
      </li>

      <li class="nav-item">
       <!--<a class="nav-link" href="#">Budget planner</a> -->
       <a><%=link_to "Find Trip To dos", trip_todos_path, class: 'nav-link' %> </a>
      </li>
      
        <li class="nav-item">
      <a><%=link_to current_user.email, edit_user_registration_path, class: 'nav-link' %> </a>
      </li>
       <li class="nav-item">
     <a><%=link_to "Sign out", destroy_user_session_path, method: :delete, class: 'nav-link' %> </a>
     </li>
     
     <% else %>
     
        <li class="nav-item">
     <a><%=link_to "Login", new_user_session_path, class: 'nav-link' %> </a>
      </li>
       <li class="nav-item">
     <a> <%=link_to "Sign Up", new_user_registration_path, class: 'nav-link' %> </a>
      </li>
      
   <% end %>
   </li>
   
    </ul>
  </div>
</nav>

<%= yield %>
</body>
</html>